### ISSUE TITLE
Ionic 2 not serving

### ISSUE THREAD

**Issue by JoshWilliams92** [Rich-Harris/tippex#13]
Error transforming app.component.ts with 'ion-compiler' plugin: rollup-plugin-typescript: Unexpected character. If this is valid Javascript, it's probably a bug in tippex.

**Comment by Rich-Harris** [comment]
> If this is valid Javascript

Tippex isn't designed to handle TypeScript – sounds like maybe the code needs to get transpiled somewhere beforehand? I don't really 'do' TypeScript so I'm not sure what more I can suggest, other than that Tippex is probably being used in a place it's not meant to be used.

**Comment by Rich-Harris** [comment]
Ah – could it be related to https://github.com/Rich-Harris/tippex/issues/12?
