### ISSUE TITLE
Handle esoteric regex/division cases

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/tippex#4]
See #3. Can't currently deal with `a++/b/g`. There are certainly others. Excluding them from the tests for now for the sake of releasing a new version that handles the vast majority of cases.

**Comment by heavyk** [comment]
I've been playing around with this now for a bit and I see you've added the test for `++/b/.abc;` - which I'm going to argue is invalid. there is no property of a regex you will ever need to increment or decrement.

if we consider that case invalid (which I believe it is), then I have a proposed fix. I've been trying to think or a case with a postfix op and a slash that's actually used.

few minutes and I'll put the PR.
